openapi: 3.0.0
info:
  title: OneApp
  description: Basic app to check social media info - Mehul Dantani
  version: 1.0.1
servers:
  - url: https://mehulroutes.herokuapp.com/api/v1
    description: Port of our application.
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /instagram:
    get:
      summary: returns a username, followers, Following and time on request made at instagram
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  following:
                    type: string
  /facebook:
    get:
      summary: returns a username, followers, Following and time on request made at instagram
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  following:
                    type: string
  /linkedin:
    get:
      summary: returns a username, followers, Following and time on request made at instagram
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: string
                  following:
                    type: string
  /{tokens}:
    get:
      summary: returns a passed parameters
      parameters:
        - name: token
          default: 5
          in: path
          schema:
            type: string
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  parameter:
                    type: string